In [8]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('pima-indians-diabetes.csv')

X = dataset.iloc[:, 0:8].values
Y = dataset.iloc[:, 8].values
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
print(X_train)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(ac)
print(cm)
#plt.plot(y_test, y_pred)

[[4.00e+00 1.83e+02 0.00e+00 ... 2.84e+01 2.12e-01 3.60e+01]
 [4.00e+00 9.90e+01 7.60e+01 ... 2.32e+01 2.23e-01 2.10e+01]
 [9.00e+00 1.24e+02 7.00e+01 ... 3.54e+01 2.82e-01 3.40e+01]
 ...
 [7.00e+00 1.14e+02 6.40e+01 ... 2.74e+01 7.32e-01 3.40e+01]
 [6.00e+00 1.25e+02 7.60e+01 ... 3.38e+01 1.21e-01 5.40e+01]
 [2.00e+00 1.29e+02 7.40e+01 ... 3.32e+01 5.91e-01 2.50e+01]]
0.8051948051948052
[[89 12]
 [18 35]]


In [1]:
# Importing the libraries
import numpy as np
from numpy import nan
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('pima-indians-diabetes.csv')

X = dataset.iloc[:, 0:8].values
Y = dataset.iloc[:, 8].values
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
print(X_train)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer(missing_values=nan, strategy='constant')
values = dataset.values
data_with_imputed_values = my_imputer.fit_transform(values)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(ac)
print(cm)

[[4.00e+00 1.83e+02 0.00e+00 ... 2.84e+01 2.12e-01 3.60e+01]
 [4.00e+00 9.90e+01 7.60e+01 ... 2.32e+01 2.23e-01 2.10e+01]
 [9.00e+00 1.24e+02 7.00e+01 ... 3.54e+01 2.82e-01 3.40e+01]
 ...
 [7.00e+00 1.14e+02 6.40e+01 ... 2.74e+01 7.32e-01 3.40e+01]
 [6.00e+00 1.25e+02 7.60e+01 ... 3.38e+01 1.21e-01 5.40e+01]
 [2.00e+00 1.29e+02 7.40e+01 ... 3.32e+01 5.91e-01 2.50e+01]]
0.8051948051948052
[[89 12]
 [18 35]]


In [2]:
dataset.isnull()

6    148     72     35      0   33.6  0.627     50      1
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
762  False  False  False  False  False  False  False  False  False
763  False  False  False  False  False  False  False  False  False
764  False  False  False  False  False  False  False  False  False
765  False  False  False  False  False  False  False  False  False
766  False  False  False  False  False  False  False  False  False

[767 rows x 9 columns]

In [7]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy import nan

# Importing the dataset
dataset = pd.read_csv('breast-cancer-wisconsin.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(ac)
print(cm)
#plt.plot(y_test, y_pred)

0.9357142857142857
[[81  4]
 [ 5 50]]


In [4]:
print(dataset)

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]


In [8]:
dataset.fillna(0)

1000025  5   1  1.1  1.2  2   1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10.0   3    2    1    2
1    1015425  3   1    1    1  2   2.0   3    1    1    2
2    1016277  6   8    8    1  3   4.0   3    7    1    2
3    1017023  4   1    1    3  2   1.0   3    1    1    2
4    1017122  8  10   10    8  7  10.0   9    7    1    4
..       ... ..  ..  ...  ... ..   ...  ..  ...  ...  ...
693   776715  3   1    1    1  3   2.0   1    1    1    2
694   841769  2   1    1    1  2   1.0   1    1    1    2
695   888820  5  10   10    3  7   3.0   8   10    2    4
696   897471  4   8    6    4  3   4.0  10    6    1    4
697   897471  4   8    8    5  4   5.0  10    4    1    4

[698 rows x 11 columns]

In [12]:
dataset.isnull().sum()

1000025     0
5           0
1           0
1.1         0
1.2         0
2           0
1.3        16
3           0
1.4         0
1.5         0
2.1         0
dtype: int64

In [9]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy import nan

# Importing the dataset
dataset = pd.read_csv('breast-cancer-wisconsin.csv')
#X = dataset.iloc[:, [2, 3]].values
X=dataset.iloc[:,0:10]
y = dataset.iloc[:, 10].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
from sklearn.impute import SimpleImputer

my_imputer = SimpleImputer(missing_values=nan, strategy='median')
values = dataset.values
data_with_imputed_values = my_imputer.fit_transform(values)
# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(ac)
print(cm)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [4]:
dataset.isnull().head(200)

1000025      5      1    1.1    1.2      2    1.3      3    1.4    1.5  \
0      False  False  False  False  False  False  False  False  False  False   
1      False  False  False  False  False  False  False  False  False  False   
2      False  False  False  False  False  False  False  False  False  False   
3      False  False  False  False  False  False  False  False  False  False   
4      False  False  False  False  False  False  False  False  False  False   
..       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
195    False  False  False  False  False  False  False  False  False  False   
196    False  False  False  False  False  False  False  False  False  False   
197    False  False  False  False  False  False  False  False  False  False   
198    False  False  False  False  False  False  False  False  False  False   
199    False  False  False  False  False  False  False  False  False  False   

       2.1  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
195  False  
196  False  
197  False  
198  False  
199  False  

[200 rows x 11 columns]

In [1]:
# Python code explaining How to
# Handle Missing Value in Dataset
  

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#dataset load  
data_sets = pd.read_csv('breast-cancer-wisconsin.csv')
  
print ("Data Head : \n", data_sets.head())
  
print ("\n\nData Describe : \n", data_sets.describe())

# All rows but all columns except last
X = data_sets.iloc[:, :-1].values
  
# TES
# All rows but only last column 
Y = data_sets.iloc[:, 3].values
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)  
  
from sklearn.linear_model import LinearRegression as lm
model=lm().fit(x_train,y_train)
y_pred=model.predict(x_test)                  
print("\n\nInput : \n", X)
print("\n\nOutput: \n", Y)
#hndling missing values  
# We will use sklearn library >> preprocessing package
# Imputer class of that package
from sklearn.impute import SimpleImputer
# Using Imputer function to replace NaN
# values with mean of that parameter value

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
  


                    
# Fitting the data, function learns the stats
imputer = imputer.fit(X[:, 1:3])
  
# fit_transform() will execute those
# stats on the input ie. X[:, 1:3]
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])
  
# filling the missing value with mean
print("\n\nNew Input with Mean Value for NaN : \n", X)
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)

Data Head : 
    1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4


Data Describe : 
             1000025           5           1         1.1         1.2  \
count  6.980000e+02  698.000000  698.000000  698.000000  698.000000   
mean   1.071807e+06    4.416905    3.137536    3.210602    2.809456   
std    6.175323e+05    2.817673    3.052575    2.972867    2.856606   
min    6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.702582e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238354e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        

ValueError: could not convert string to float: '?'